### ISSUE TITLE
扫描结果的ping值为何比CMD的ping要高出十几倍？

### ISSUE THREAD

**Issue by ghost** [johnsonz/go-checksni#10]
首先谢谢作者出了低性能模式。
然后就是这个问题，一个ip，cmd得出30ms，sni_ok.txt里却是500多ms。可能是ping的方法不同？这样一来config就不好设置了，有些ip cmdping的不高，但可能被过滤掉。

**Comment by johnsonz** [comment]
这里是整个HTTPS的请求响应时间，包含了SSL握手时间，而不是简单的ping，如果指定了多个server name，该值则是平均值

**Comment by ghost** [comment]
谢谢回复！
