### ISSUE TITLE
always_check_all_ip":false+低性能模式，中断就从头开始

### ISSUE THREAD

**Issue by ghost** [johnsonz/go-checksni#11]

**Comment by lhwlhw** [comment]
还有一事，刚刚关闭服务器上的程序后发现扫描得到的sni_ok少了好几个！不知道怎么出的问题

**Comment by johnsonz** [comment]
低性能模式不会一次性将ip全部读取到内存（读取一个就扫描一个），也就很难去判断哪些ip是已经扫描过的，`always_check_all_ip`设置是无效的，这个模式是给那些ip太多且内存较小的用户用的。

**Comment by lhwlhw** [comment]
@johnsonz 所以我是认为严格按顺序一行一行读取很重要，我不是做程序员的，可能这样做在编程上很困难？
如我之前的构想的，做到这样严格按顺序，用扫描结果最后一个ip，去判断ip扫描到哪，应该会比较轻松吧？

**Comment by lhwlhw** [comment]
@johnsonz 又发现个有趣的问题，recorded的sniip竟然还会出现在sniip_no.txt里= =
