### ISSUE TITLE
内存/CPU占用非常大。希望能够改进

### ISSUE THREAD

**Issue by j4Uq** [johnsonz/go-checksni#6]
隔壁https://github.com/hjolin/go-checkip扫同样大小的iprange时就占用很低，希望开发者能参考一下，谢谢

**Comment by j4Uq** [comment]
好像内存泄漏了，刚刚挂机半小时不到电脑就自动重启了。。。。

**Comment by johnsonz** [comment]
参见 [v2.0](https://github.com/johnsonz/go-sni-detector/releases/tag/v2.0) 

对于小内存机器请将`soft_mode`置为`true`
