### ISSUE TITLE
不输出失败IP怎么弄？

### ISSUE THREAD

**Issue by ghost** [johnsonz/go-checksni#7]
失败IP没啥用吧

**Comment by johnsonz** [comment]
输出失败ip可以在上次中断的地方继续扫描

**Comment by ghost** [comment]
@johnsonz 我有个小建议，我的VPS比较渣，但是又想快点扫，于是线程调高，经常exit，虽说中断可以继续，但有时候是扫描完成，我以为是中断，扫描完成后再扫描又会重新扫描，希望能做个提示，你已经扫描完成是否再来一遍这样的。

**Comment by johnsonz** [comment]
请将`"always_check_all_ip":true`置为false，默认是执行完全扫描

**Comment by ghost** [comment]
@johnsonz 谢谢！但是还有一个问题，如果扫描量巨大的时候中断了，要再开始会等很久，这时候我发现你的程序不是严格按照sniip.txt行的顺序走的，貌似是随机读取一行扫描的？如果你可以严格按照行的顺序，我就可以直接看最后扫描到的IP，然后把之前扫过的段直接删掉，再重新开始，比你的程序重新接上中断处要快不少。

**Comment by johnsonz** [comment]
初始化的时候会有ip去重，乱序扫描

**Comment by lhwlhw** [comment]
这样啊？其实我有一个增加效率的设想(YY)，首先不输出失败IP，但是每扫描比如255(或者更大)个IP时你的程序自动修改sniip.txt为剩下的。比如1.0.0.0-1.0.5.255，扫描完1.0.0.0-1.0.0.255自动修改sniip里的数据为1.0.1.0-1.0.5.255 。
这样一来就不必输出巨大的失败的IP，中断时也可以知道断在哪，继续时也可以马上开始。你觉得我这YY可行不？

**Comment by lhwlhw** [comment]
任务一多内存占用也是巨大的，想必是一口气读取了所有IP，希望能改成分段式任务。(我瞎猜的)
